name: Deploy
on:
  push:
    branches: contentType
  pull_request:
    branches: contentType

jobs:
  deploy:
    name: Development deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.2
      - name: Build step
        run: deno task build # ğŸ“ Update the build command(s)

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "soft-bobcat-75"
          entrypoint: "server/index.ts"  # ğŸ“ Update the entrypoint
          root: "." # ğŸ“ Update the root
